server:
  port: 8006
spring:
  application:
    name: consul-provider-payment
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/springcloud?serverTimezone=Asia/Shanghai&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    #\u914D\u7F6Econsul
    consul:
      #consul\u8FDE\u63A5\u5730\u5740
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}  #127.0.0.1

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.atguigu.springcloud.bean  #\u6240\u6709bean\u522B\u540D\u6240\u5728\u7C7B\u5305

  configuration:
    map-underscore-to-camel-case: true
